CREATE TABLE RECIPE
(
    ID         INTEGER     NOT NULL PRIMARY KEY,
    SOURCE     VARCHAR(32) NOT NULL,
    IS_ENABLED INTEGER(1),
    DURATION   INTEGER,
    EU_T       INTEGER
);

CREATE TABLE RECIPE_ITEM
(
    RECIPE_ID INTEGER         NOT NULL,
    ITEM_ID   INTEGER         NOT NULL,
    SLOT      INTEGER         NULL,
    AMOUNT    INTEGER /*NOT*/ NULL,
    IS_OUTPUT INTEGER(1)      NOT NULL
);

CREATE INDEX RECIPE_ITEM_RECIPE_ID
    ON RECIPE_ITEM (RECIPE_ID, ITEM_ID);
CREATE INDEX RECIPE_ITEM_ITEM_ID
    ON RECIPE_ITEM (ITEM_ID, IS_OUTPUT);

CREATE TABLE ITEM
(
    ID             INTEGER NOT NULL PRIMARY KEY,
    LOCALIZED_NAME VARCHAR(128),
    INTERNAL_NAME  VARCHAR(32),
    IS_FLUID       INTEGER(1),
    CONFIG         INTEGER NULL
);
