CREATE TABLE RECIPE
(
    ID         INTEGER     NOT NULL PRIMARY KEY,
    SOURCE     VARCHAR(32) NOT NULL,
    IS_ENABLED INTEGER(1),
    DURATION   INTEGER,
    EU_T       INTEGER
);

CREATE TABLE ORE_DICT_GROUP
(
    ID   INTEGER     NOT NULL PRIMARY KEY,
    NAME VARCHAR(32) NOT NULL
);

CREATE TABLE ORE_DICT_ITEM
(
    ORE_DICT_ID INTEGER NOT NULL,
    ITEM_ID     INTEGER NOT NULL
);

CREATE TABLE RECIPE_ITEM
(
    RECIPE_ID   INTEGER         NOT NULL,
    ITEM_ID     INTEGER         NULL,
    ORE_DICT_ID INTEGER         NULL,
    SLOT        INTEGER         NULL,
    AMOUNT      INTEGER /*NOT*/ NULL,
    CHANCE      INTEGER         NULL,
    IS_OUTPUT   INTEGER(1)      NOT NULL
);

CREATE INDEX RECIPE_ITEM_RECIPE_ID
    ON RECIPE_ITEM (RECIPE_ID, ITEM_ID);
CREATE INDEX RECIPE_ITEM_ITEM_ID
    ON RECIPE_ITEM (ITEM_ID, IS_OUTPUT);

CREATE TABLE ITEM
(
    ID             INTEGER NOT NULL PRIMARY KEY,
    LOCALIZED_NAME VARCHAR(128),
    INTERNAL_NAME  VARCHAR(32),
    IS_FLUID       INTEGER(1),
    DAMAGE         INTEGER NULL
);
